name: massive-serve
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - faiss-gpu
  - pytorch
  - pip:
    - flask
    - flask-cors
    - transformers
    - numpy
    - tqdm
    - sentence-transformers